services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Alexispe\SyliusRoundUpPlugin\Controller\Shop\RoundUpController:
        arguments:
            $metadata: '@=service("sylius.resource_registry").get("sylius.order_item")'
            $entityManager: '@sylius.manager.order'
            $authorizationChecker: '@sylius.resource_controller.authorization_checker.disabled'
            $adjustmentFactory: '@sylius.factory.adjustment'
            $roundUpPriceCalculator: '@alexispe_sylius_round_up_plugin.calculator.round_up_price_calculator'

    alexispe_sylius_round_up_plugin.processor.round_up_processor:
        class: Alexispe\SyliusRoundUpPlugin\Processor\RoundUpProcessor
        arguments:
            - '@sylius.factory.adjustment'
            - '@alexispe_sylius_round_up_plugin.calculator.round_up_price_calculator'
        tags:
            - { name: sylius.order_processor, priority: 90 }
    
    alexispe_sylius_round_up_plugin.calculator.round_up_price_calculator:
        class: Alexispe\SyliusRoundUpPlugin\Calculator\RoundUpPriceCalculator
