alexispe_sylius_round_up_plugin_shop_round_up_cart:
    path: /cart/round-up
    methods: [POST]
    defaults:
        _controller: Alexispe\SyliusRoundUpPlugin\Controller\Shop\RoundUpController::addToCart
        _format: json
        _sylius:
            redirect:
                route: sylius_shop_cart_summary
                parameters: {}

alexispe_sylius_round_up_plugin_shop_undo_round_up_cart:
    path: /cart/round-up
    methods: [DELETE]
    defaults:
        _controller: Alexispe\SyliusRoundUpPlugin\Controller\Shop\RoundUpController::removeFromCart
        _format: json
        _sylius:
            redirect:
                route: sylius_shop_cart_summary
                parameters: {}
