# Delete these routes and define your own shop routes here

alexispe_sylius_round_up_plugin_shop_round_up_cart:
    path: /cart/round-up
    methods: [POST]
    defaults:
        _controller: Alexispe\SyliusRoundUpPlugin\Action\Shop\RoundUpCartAction
        _format: json
        _sylius:
            redirect:
                route: sylius_shop_cart_summary
                parameters: {}
            flash: sylius.cart.add_item
